# See https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main
  repo: danielmoessner/gatsby-netlifycms.tortuga-webdesign.de

# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

# See https://www.netlifycms.org/docs/configuration-options/#locale
locale: de

# See https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: https://gatsby-netlifycms.tortuga-webdesign.de

# See https://www.netlifycms.org/docs/configuration-options/#site-url
site_url: https://gatsby-netlifycms.tortuga-webdesign.de

# See https://www.netlifycms.org/docs/configuration-options/#media-folder
media_folder: /content/media

# See https://www.netlifycms.org/docs/configuration-options/#public-folder
public_folder: ../media

# See https://www.netlifycms.org/docs/collection-types/
collections:
  - name: page
    label: Seiten
    label_singular: Seite
    delete: false
    editor:
      preview: false
    files:
      - file: content/pages/home.yml
        label: Startseite
        name: home
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: home }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Titel farbig, name: titleColor, widget: string, required: false }
              - { label: Text, name: text, widget: text }
              - { label: Button links, name: buttonLeft, widget: text }
              - { label: Button rechts, name: buttonRight, widget: text }
              - { label: Bild, name: image, widget: image }
          - label: Krankheitsbilder
            name: illness
            widget: object
            fields: 
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: string }
          - label: Team
            name: team 
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Button, name: button, widget: string }
          - label: Sprechstunden
            name: appointment
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - label: Anti Aging
            name: antiAging
            widget: object
            fields:
              - { label: Bild, name: image, widget: image }
              - { label: Vortitel, name: pretitle, widget: string }
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Button, name: button, widget: string }
      
      - file: content/pages/illness.yml
        label: Krankheitsbilder
        name: illness
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: illness }
          - { label: Vortitel, name: pretitle, widget: string }


      - file: content/pages/nonSurgicalTherapies.md
        label: Nicht-operative Therapien
        name: nonSurgicalTherapies
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: non-surgical-therapies }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Vortitel, name: pretitle, widget: string }
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - label: Inhalt
            name: body
            widget: markdown
            hint: Bitte nur Überschrift 2-6 verwenden für SEO.
     
      - file: content/pages/operation.yml
        label: Operationen
        name: operation
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: operation }
          - { label: Vortitel, name: pretitle, widget: string }

      - file: content/pages/team.yml
        label: Team
        name: team
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: contact }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }    
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: string }     

      - file: content/pages/contact.yml
        label: Kontakt
        name: contact
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: contact }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }     
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: string }     
          - label: Kontakt
            name: contact
            widget: object
            fields: 
              - { label: Titel 1, name: title1, widget: string }
              - { label: Text 1, name: text1, widget: text }
              - { label: Titel 2, name: title2, widget: string }
              - { label: Titel 3, name: title3, widget: string }
      
      - file: content/pages/imprint.md
        label: Impressum
        name: imprint
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: imprint }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Vortitel, name: pretitle, widget: string }
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - { label: Inhalt, name: body, widget: markdown, hint: Bitte nur Überschrift 2-6 verwenden für SEO. }

      - file: content/pages/dataProtection.md
        label: Datenschutz
        name: dataProtection
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: dataProtection }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Vortitel, name: pretitle, widget: string }
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
          - { label: Inhalt, name: body, widget: markdown, hint: Bitte nur Überschrift 2-6 verwenden für SEO. }

  - name: member
    label: Teammitglieder
    label_singular: Teammitglied
    editor:
      preview: true
    folder: content/member
    slug: '{{fields.slug}}'
    create: true
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: member }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Untertitel, name: subtitle, widget: string }
      - { label: Bild, name: image, widget: image }
      - { label: Auszug, name: excerpt, widget: text }
      - { label: Inhalt, name: body, widget: markdown }

  - name: illness
    label: Krankheitsbilder
    label_singular: Krankheitsbild
    editor:
      preview: true
    extension: md
    folder: content/illness
    slug: '{{fields.slug}}'
    create: true
    preview_path: krankheitsbild/{{fields.slug}}
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: illness }
      - label: Meta
        name: meta
        widget: object
        fields:
          - { label: Titel, name: title, widget: string }
          - label: Beschreibung
            name: description
            widget: text
          - { label: Bild, name: image, widget: image, required: false }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Auszug, name: excerpt, widget: text }
      - label: Inhalt
        name: body
        widget: markdown
        hint: Bitte nur Überschrift 2-6 verwenden für SEO.

  - name: operation
    label: Operationen
    label_singular: Operationen
    editor:
      preview: true
    extension: md
    folder: content/operation
    slug: '{{fields.slug}}'
    create: true
    preview_path: operation/{{fields.slug}}
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: operation }
      - label: Meta
        name: meta
        widget: object
        fields:
          - { label: Titel, name: title, widget: string }
          - label: Beschreibung
            name: description
            widget: text
          - { label: Bild, name: image, widget: image, required: false }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Auszug, name: excerpt, widget: text }
      - label: Inhalt
        name: body
        widget: markdown
        hint: Bitte nur Überschrift 2-6 verwenden für SEO.

  - name: category
    label: Kategorien
    label_singular: Kategorie
    editor:
      preview: false
    folder: content/categories
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: category }
      - { label: Titel, name: title, widget: string }

  - name: 'setting'
    label: Einstellungen
    label_singular: Einstellung
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: Global
        name: 'global-settings'
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: global }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Svg Logo, name: logo, widget: text, hint: Bitte nur ändern wenn man weiß was man macht. }
      - file: content/settings/appointments.yml
        label: Sprechstunden
        name: appointments
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: appointments }
          - label: Sprechstunden
            widget: list
            name: appointments
            fields:
              - { label: Tag, name: day, widget: string }
              - { label: Öffnungszeiten, name: openingHours, widget: string }
      - file: content/settings/contact.yml
        label: Kontaktinformationen
        name: contact
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: contact }
          - { label: Telefon, name: phone, widget: string }
          - { label: E-Mail, name: email, widget: string }
          - { label: Adresse, name: address, widget: text }
      - file: content/settings/navigation.yml
        label: Navigation
        name: navigation
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: footer }
          - { label: Link 1, name: link1, widget: string }
          - { label: Link 2, name: link2, widget: string }
          - { label: Link 3, name: link3, widget: string }
          - { label: Link 4, name: link4, widget: string }
          - { label: Link 5, name: link5, widget: string }
          - { label: Link 6, name: link6, widget: string }
          - { label: Mobil Link 2, name: mobileLink2, widget: string }
          - { label: Mobil Link 4, name: mobileLink4, widget: string }
      - file: content/settings/footer.yml
        label: Footer
        name: footer
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: footer }
          - { label: Text, name: text, widget: text }
          - { label: Spalte 1, name: column1, widget: string }
          - { label: Spalte 2, name: column2, widget: string }
          - { label: Spalte 3, name: column3, widget: string }
          - { label: Spalte 4, name: column4, widget: string }
          - { label: Link 1-1, name: link11, widget: string }
          - { label: Link 1-2, name: link12, widget: string }
          - { label: Link 1-3, name: link13, widget: string }
          - { label: Link 1-4, name: link14, widget: string }
          - { label: Link 4-1, name: link41, widget: string }
          - { label: Link 4-2, name: link42, widget: string }